#!/usr/bin/env node

const server = require('./lib/server');
const yargs = require('yargs');
const config = require('./package.json');

yargs
    .command('serve [port]', 'Start the Pancake server.', (yargs) => {
        yargs
            .positional('port', {
                describe: 'The port to run the server on.',
                default: 80
            })
            .positional('path', {
                describe: 'A directory to serve.',
                default: process.cwd()
            })
    }, (argv) => {
        server(argv.path, argv.port);
    })
    .command ('version', 'Displays the current installed version of Pancake.', (yargs) => {
        console.log(`Pancake v${config.version}`);
    });